services:
  web:
    image: ${WEB_IMAGE:-ghcr.io/shubkb07/wp-local:0.0.9-alpha}
    container_name: ${CONTAINER_NAME:-local-wp-web}
    restart: unless-stopped
    ports:
      - "${APACHE_HTTP_PORT:-8080}:80"
    environment:
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-local_root_password}
      PHP_MEMORY: ${PHP_MEMORY:-512M}
      CLOUDFLARED_API_KEY: ${CLOUDFLARED_API_KEY:-}
      CLOUDFLARED_SITES: ${CLOUDFLARED_SITES:-}
      SITES: ${SITES:-apple.local,meow.local}
      NO_DELETE_SITES: ${NO_DELETE_SITES:-}
    volumes:
      - ${LOCAL_WP_DATA_PATH:-data}:/data
      - ${WP_SITES_PATH:-./data/wp-sites}:/data/wp-sites
      - ${LOCAL_WP_ENV_FILE:-./.env}:/data/.env
      - db-data:/var/lib/mysql
      - redis-data:/var/lib/redis

volumes:
  data:
  db-data:
  redis-data:
